<a href="https://colab.research.google.com/github/poojashreeNS/Dimensionality_Reduction/blob/main/Dimensionality_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import time

In [2]:
# For plotting
import plotly.io as plt_io
import plotly.graph_objects as go
%matplotlib inline

In [ ]:
!pip install umap-learn[plot]
!pip install holoviews
!pip install -U ipykernel

In [27]:
#PCA
from sklearn.decomposition import PCA
#TSNE
from sklearn.manifold import TSNE
#UMAP
import umap
#LLE
from sklearn.manifold import LocallyLinearEmbedding as LLE
#Isomap
from sklearn.manifold import Isomap
#SVD
from sklearn.decomposition import TruncatedSVD

In [8]:
train = pd.read_csv('/content/sign_mnist_test.csv')
train.head()

label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      6     149     149     150  ...       106       112       120       107
1      5     126     128     131  ...       184       184       182       180
2     10      85      88      92  ...       226       225       224       222
3      0     203     205     207  ...       230       240       253       255
4      3     188     191     193  ...        49        46        46        53

[5 rows x 785 columns]

In [9]:
#picking only the first 10 labels
train = train[train['label'] < 10]
# Setting the label and the feature columns
y = train.loc[:,'label'].values
x = train.loc[:,'pixel1':].values

Implementing Plotting functions

In [10]:
def plot_2d(component1, component2):
    
    fig = go.Figure(data=go.Scatter(
        x = component1,
        y = component2,
        mode='markers',
        marker=dict(
            size=10,
            color=y, #set color equal to a variable
            colorscale='Rainbow', # one of plotly colorscales
            showscale=True,
            line_width=1
        )
    ))
    fig.update_layout(margin=dict( l=100,r=100,b=100,t=100),width=2000,height=1200)                 
    fig.layout.template = 'plotly_dark'
    
    fig.show()

In [11]:
def plot_3d(component1,component2,component3):

  fig = go.Figure(data=[go.Scatter3d(
        x=component1,
        y=component2,
        z=component3,
        mode='markers',
        marker=dict(
            size=5,
            color=y,                # set color to an array/list of desired values
            colorscale='Rainbow',   # choose a colorscale
            opacity=1,
            line_width=1
        )
    )])
  # tight layout
  fig.update_layout(margin=dict(l=50,r=50,b=50,t=50),width=1800,height=1000)
  fig.layout.template = 'plotly_dark'
    
  fig.show()

Standardizing dataset

In [12]:
from sklearn.preprocessing import StandardScaler
## Standardizing the data
x = StandardScaler().fit_transform(x)

# **Implementing PCA**

In [ ]:
start = time.time()
pca = PCA(n_components=3)
principalComponents = pca.fit_transform(x)
print('Duration: {} seconds'.format(time.time() - start))
principal = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2','principal component 3'])

Duration: 0.3520987033843994 seconds


PCA_2D

In [ ]:
plot_2d(principalComponents[:, 0],principalComponents[:, 1])

PCA_3D

In [ ]:
plot_3d(principalComponents[:, 0],principalComponents[:, 1],principalComponents[:, 2])

# **Implementing t-SNE**

In [ ]:
start = time.time()
pca_50 = PCA(n_components=50)
pca_result_50 = pca_50.fit_transform(x)
tsne = TSNE(random_state = 42, n_components=3,verbose=0, perplexity=40, n_iter=400).fit_transform(pca_result_50)
print('Duration: {} seconds'.format(time.time() - start))

Duration: 37.894346475601196 seconds


t-SNE_2D

In [ ]:
plot_2d(tsne[:, 0],tsne[:, 1])

t-SNE_3D

In [ ]:
plot_3d(tsne[:, 0],tsne[:, 1],tsne[:, 2])

# **Implementation of UMAP**

In [ ]:
start = time.time()
reducer = umap.UMAP(random_state=42,n_components=3)
embedding = reducer.fit_transform(x)
print('Duration: {} seconds'.format(time.time() - start))

UMAP_2D

In [ ]:
plot_2d(reducer.embedding_[:, 0],reducer.embedding_[:, 1])

UMAP_3D

In [ ]:
plot_3d(reducer.embedding_[:, 0],reducer.embedding_[:, 1],reducer.embedding_[:, 2])

# **Implementation of LLE**

In [23]:
def run_lle(num_neighbors, dims, mthd, data):
    # Specify LLE parameters
    embed_lle = LLE(n_neighbors=num_neighbors,
                    n_components=dims, 
                    reg=0.001,
                    eigen_solver='auto',
                    method=mthd, 
                    modified_tol=1e-12,
                    neighbors_algorithm='auto',
                    random_state=42,
                    n_jobs=-1
                   )
    # Fit and transofrm the data
    result = embed_lle.fit_transform(data)
    
    # Return results
    return result

LLE_2D

In [14]:
std_lle_res=run_lle(num_neighbors=30, dims=2, mthd='standard', data=x)
plot_2d(std_lle_res[:, 0],std_lle_res[:, 1] )

LLE_3D

In [18]:
std_lle_res=run_lle(num_neighbors=30, dims=3, mthd='modified', data=x)
plot_3d(std_lle_res[:, 0], std_lle_res[:, 1], std_lle_res[:, 2])

# **Implementation of Isomap**

In [22]:
def run_isomap(num_neighbors, dims, data):
    # Specify Isomap parameters
    embed_isomap = Isomap(n_neighbors=num_neighbors, n_components=dims, n_jobs=-1)
    
    # Fit and transofrm the data
    result = embed_isomap.fit_transform(data)
    
    # Return results
    return result    

Isomap_2D

In [24]:
isomap_res=run_isomap(num_neighbors=30, dims=2, data=x)
plot_2d(isomap_res[:, 0], isomap_res[:, 1])

[[ -2.57952027  45.55779049]
 [ 19.3330679    2.35683691]
 [-11.4473394  -23.24483809]
 ...
 [ 10.76698079 -17.27879299]
 [-18.93096011 -51.2927459 ]
 [ 28.86483432  -5.60117552]]


Isomap_3D

In [25]:
isomap_res=run_isomap(num_neighbors=30, dims=3, data=x)
plot_3d(isomap_res[:,0], isomap_res[:, 1], isomap_res[:, 2])

[[ -2.57952027  45.55779049 -11.10928201]
 [ 19.3330679    2.35683691   2.68400811]
 [-11.4473394  -23.24483809   4.37008567]
 ...
 [ 10.76698079 -17.27879299 -43.85010264]
 [-18.93096011 -51.2927459    3.15320809]
 [ 28.86483432  -5.60117552 -43.55734031]]


# **Implementation of SVD**

In [31]:
svd = TruncatedSVD(n_components=2)
X_reduced = svd.fit_transform(x)
plot_2d(X_reduced[:, 0], X_reduced[:, 1])

In [33]:
svd = TruncatedSVD(n_components=3)
X_reduced = svd.fit_transform(x)
plot_3d(X_reduced[:, 0], X_reduced[:, 1], X_reduced[:, 2])